server:
  port: 8080

spring:
  application:
    name: avaloq-dice-service
  datasource:
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS dice
    username: sa
    driver-class: org.h2.Driver
    platform: h2
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60001
      maxLifetime: 180001
      connection-timeout: 5001
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  file: logs/avaloq-dice-service
  level:
    com:
      zaxxer:
        hikari: debug